### ISSUE TITLE
Add instructions for obtaining iTerm 2.9

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/term-img-cli#1]
So I'm at iTerm 2.1.4 and it says it's the latest version.

Any chance of adding instructions as to how to get 2.9?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/term-img-cli/commit/6406d3aaa40b917c97a242adafd7d38620e7b508 The "Test release".

**Comment by Qix-** [comment]
:+1:
